// Build Hershey font data → stroke-font glyph table.
// Run with: node tools/build-hershey.mjs
// Reads futural.jhf (public domain), writes src/pcb/modules/hershey-data.js
import { readFileSync, writeFileSync } from 'node:fs';

const txt = readFileSync('futural.jhf', 'utf8');

// Pre-process: many Hershey files wrap long glyphs onto continuation
// lines (no leading serial). We rejoin those into single records.
const rawLines = txt.split(/\r?\n/);
const records = [];
let buf = '';
for (const line of rawLines) {
    if (!line) continue;
    // A new record starts with 5 digits then 3 spaces/digits for count.
    if (/^\s*\d{1,5}\s*\d+/.test(line) && /^\s*\d+\s+\d+/.test(line.slice(0, 8))) {
        if (buf) records.push(buf);
        buf = line;
    } else {
        buf += line;
    }
}
if (buf) records.push(buf);

const ORD_R = 'R'.charCodeAt(0);
const glyphs = [];
for (const rec of records) {
    // chars 0..4 = serial; 5..7 = pair count; 8.. = pairs
    const count = parseInt(rec.slice(5, 8), 10);
    const data = rec.slice(8);
    const left = data.charCodeAt(0) - ORD_R;
    const right = data.charCodeAt(1) - ORD_R;
    const strokes = [];
    let cur = [];
    for (let i = 1; i < count; i++) {
        const xc = data.charCodeAt(2 * i);
        const yc = data.charCodeAt(2 * i + 1);
        if (xc === ORD_R && data[2 * i + 1] === 'R' && false) {
            // (placeholder)
        }
        if (data[2 * i] === ' ' && data[2 * i + 1] === 'R') {
            if (cur.length) strokes.push(cur);
            cur = [];
            continue;
        }
        const x = xc - ORD_R;
        const y = yc - ORD_R;
        cur.push([x, y]);
    }
    if (cur.length) strokes.push(cur);
    glyphs.push({ left, right, strokes });
}

// Normalize. Hershey "ascender top" is typically y = -12 (rows go negative
// upward from baseline). For cap height we use the standard simplex value:
// uppercase caps span roughly y = -12 (top) to y = 9 (baseline of caps).
// In jhf, F=-12, V=4, Z=8.  Top of caps = F (-12), baseline = V (4).
// So cap height = 4 - (-12) = 16 jhf units. Map to [0..1].
const CAP_TOP = -12;       // jhf y at top of caps
const BASELINE = 4;         // jhf y at baseline (rows below = descenders)
const CAP_H = BASELINE - CAP_TOP; // 16

function mapY(y) {
    // jhf y grows downward; we want y=0 at baseline, y=1 at cap-top.
    return (BASELINE - y) / CAP_H;
}
function mapX(x, left) {
    return (x - left) / CAP_H;
}

const out = {};
for (let i = 0; i < glyphs.length; i++) {
    const ch = String.fromCharCode(32 + i);
    const g = glyphs[i];
    const w = (g.right - g.left) / CAP_H;
    const s = g.strokes.map(stroke =>
        stroke.map(([x, y]) => [mapX(x, g.left), mapY(y)])
    );
    out[ch] = { w: +w.toFixed(3), s: s.map(st => st.map(([x, y]) => [+x.toFixed(3), +y.toFixed(3)])) };
}

// Emit compact JS.
let js = '// Hershey Sans Serif (Roman Simplex / futural). Public domain.\n';
js += '// Auto-generated by tools/build-hershey.mjs. Do not edit by hand.\n';
js += 'export const HERSHEY = {\n';
for (const ch of Object.keys(out)) {
    const g = out[ch];
    const key = JSON.stringify(ch);
    const s = '[' + g.s.map(st => '[' + st.map(p => '[' + p.join(',') + ']').join(',') + ']').join(',') + ']';
    js += `  ${key}: { w: ${g.w}, s: ${s} },\n`;
}
js += '};\n';
writeFileSync('src/pcb/modules/hershey-data.js', js);
console.log('wrote', Object.keys(out).length, 'glyphs to src/pcb/modules/hershey-data.js');
